/*
 * Alle Texte der App an einer Stelle, wie lang/de.php im Werkzeug. Englisch
 * wird eine zweite Tabelle (Spec/01_Vorschlaege.md, 9.4). Die Seiten tragen
 * nur Schluessel in data-t; fuellen() setzt die Texte ein.
 */
(function (wurzel, fabrik) {
  if (typeof module === 'object' && module.exports) module.exports = fabrik();
  else wurzel.Texte = fabrik();
}(this, function () {
  'use strict';

  const DE = {
    'app.name': 'Konsensieren im Raum',
    'suite.name': 'Konsensieren',
    'suite.aria': 'Wo abgestimmt wird',
    'suite.online': 'Online',
    'suite.raum': 'Im Raum',
    'nav.anleitung': 'Anleitung',
    'nav.menue': 'Menü',
    'allgemein.zurueck': 'Zurück',
    'allgemein.startseite': 'Zur Startseite',
    'allgemein.kein_speicher': 'Dein Browser lässt die App nichts speichern, etwa im privaten Modus. Lädst du die Seite neu, ist die Runde weg.',
    'fuss.fassung': 'Fassung {v}',
    'fuss.impressum': 'Impressum',
    'fuss.quelltext': 'Quelltext',

    'start.fuehrung': 'Die Vorschläge stehen an der Tafel. Die App zählt, was die Gruppe zeigt: Karten, Finger oder Zahlen, die jemand sagt.',
    'start.moderieren': 'Ich moderiere',
    'start.fortsetzen': 'Laufende Runde fortsetzen',
    'start.ergebnis': 'Letztes Ergebnis ansehen',
    'start.neue_runde': 'Neue Runde',
    'start.karten': 'Karten drucken',
    'start.sitzung_beenden': 'Sitzung beenden',
    'start.sitzung_beenden_dazu': 'Löscht alles, was sich die App gemerkt hat. Nach zwölf Stunden ohne Eingabe geschieht das von selbst.',
    'start.wie': 'Wie läuft eine Runde?',
    'start.wie1': 'Die Vorschläge stehen nummeriert an der Tafel, dazu die Passivlösung P: Es bleibt, wie es ist.',
    'start.wie2': 'Zu jedem Vorschlag zeigen alle, wie weit sie mitgehen, von 0 („geht gar nicht“) bis 10 („voll dabei“), mit Karten oder einer Hand auch von 0 bis 5. Du tippst ein, was du siehst.',
    'start.wie3': 'Die App rechnet wie das Online-Werkzeug: Durchschnitt der abgegebenen Werte, Enthaltung zählt nicht, die Passivlösung ist die Messlatte. Das Ergebnis schreibst du an die Tafel.',

    'start.anleitung': 'Ausführliche Anleitung',
    'start.online': 'Nicht alle im selben Raum?',
    'start.online_link': 'Dann nimm das Online-Werkzeug.',

    'neu.titel': 'Neue Runde',
    'neu.anwesende': 'Wie viele sind da?',
    'neu.anwesende_dazu': 'Alle, die mitbewerten. Daran misst die App, ob ein Vorschlag genug Bewertungen hat.',
    'neu.anwesende_fehlt': 'Trag ein, wie viele da sind, zwischen 1 und 99.',
    'neu.skala': 'Womit wird gezeigt?',
    'neu.skala10': '0 bis 10',
    'neu.skala10_dazu': 'Zwei Hände, gesagte Zahlen oder Zettel, wie im Online-Werkzeug.',
    'neu.skala5': '0 bis 5',
    'neu.skala5_dazu': 'Karten oder eine Hand. Die App rechnet mit dem Doppelten, damit das Ergebnis zur Skala von 0 bis 10 passt. Gut bis etwa zehn Personen.',
    'neu.passiv': 'Passivlösung P als erste Zeile',
    'neu.passiv_dazu': '„Es bleibt, wie es ist“ wird mitbewertet und ist die Messlatte. Ausschalten nur, wenn es kein Bisheriges gibt, etwa bei einer Terminwahl.',
    'neu.anzeige': 'Offen oder verdeckt?',
    'neu.offen': 'offen',
    'neu.offen_dazu': 'Alle zeigen ihre Werte im Raum.',
    'neu.verdeckt': 'verdeckt',
    'neu.verdeckt_dazu': 'Karten nur dir zeigen oder das Handy als Urne herumgeben. Beim Erfassen stehen nur Zähler auf dem Schirm, im Ergebnis nur Verteilungen und Kennzahlen.',
    'neu.einwaende': 'Nur ein Vorschlag? Frag zuerst, ob es Einwände gibt. Bleiben alle Hände unten, ist er angenommen.',
    'neu.beginnen': 'Runde beginnen',

    'stepper.weniger': 'eine Person weniger',
    'stepper.mehr': 'eine Person mehr',

    'erfassen.titel': 'Erfassen',
    'erfassen.skala10': '0 bis 10',
    'erfassen.skala5': '0 bis 5, wird verdoppelt',
    'erfassen.offen': 'offen',
    'erfassen.verdeckt': 'verdeckt',
    'erfassen.ohne_passiv': 'ohne Passivlösung',
    'erfassen.anwesende': 'Anwesende',
    'erfassen.art': 'Wie wird erfasst?',
    'art.vorschlag': 'je Vorschlag',
    'art.vorschlag_dazu': 'Karten, Finger',
    'art.wert': 'je Wert',
    'art.wert_dazu': 'Hände zählen',
    'art.person': 'je Person',
    'art.person_dazu': 'Zettel, Urne',
    'erfassen.zeilen': 'Zeilen',
    'zeile.name_p': 'Passivlösung',
    'zeile.name': 'Vorschlag {n}',
    'zeile.chip_aria': '{name}, {n} von {g} erfasst',
    'erfassen.zaehler': '{n} von {g} erfasst',
    'erfassen.zu_viele': '{n} von {g} erfasst: mehr als Anwesende. Eine Eingabe zu viel?',
    'erfassen.kette': 'Eingaben',
    'erfassen.kette_leer': 'noch keine',
    'erfassen.rueckgaengig': 'Rückgängig',
    'erfassen.vorher_aria': 'zur vorigen Zeile',
    'erfassen.weiter': 'Weiter zu {name}',
    'erfassen.zeile_leeren': 'Eingaben dieser Zeile löschen',
    'erfassen.wert_hinweis': 'Frag nacheinander „Wer hat {a}?“, „Wer hat {b}?“ und so weiter, und trag ein, wie viele Hände oben sind.',
    'erfassen.wer_hat': 'Wer hat {w}?',
    'erfassen.anzahl_aria': 'Anzahl der {w}',
    'erfassen.person_hinweis': 'Eine Person, alle Zeilen: die Werte der Reihe nach eintippen. Mit „Zettel fertig“ zählt der Zettel, und ein leerer beginnt.',
    'erfassen.person_verdeckt': 'Gib das Handy der Person, die bewertet. Nach „Zettel fertig“ ist ihr Zettel vom Schirm verschwunden.',
    'erfassen.zettel_fertig': 'Zettel fertig',
    'erfassen.zettel_verwerfen': 'Neu anfangen',
    'erfassen.zettel_keiner': 'Noch kein Zettel erfasst.',
    'erfassen.zettel_eins': '1 Zettel erfasst.',
    'erfassen.zettel_zahl': '{n} Zettel erfasst.',
    'erfassen.zettel_gezaehlt': 'Zettel {nr} zählt. Der nächste kann beginnen.',
    'erfassen.zettel_loeschen': 'löschen',
    'erfassen.zettel_zuruecknehmen': 'Letzten Zettel zurücknehmen',
    'erfassen.ergebnis': 'Ergebnis ansehen',
    'taste.enthaltung': 'Enthaltung',

    'bestaetigen.neue_runde': 'Die laufende Runde ist noch nicht abgeschlossen. Trotzdem eine neue beginnen? Was bisher erfasst ist, wird gelöscht.',
    'bestaetigen.sitzung_beenden': 'Sitzung beenden? Die Runde und das letzte Ergebnis werden gelöscht.',
    'bestaetigen.zeile_leeren': 'Alle Eingaben für {name} löschen?',
    'bestaetigen.entwurf_verwerfen': 'Diesen Zettel verwerfen und neu anfangen?',
    'bestaetigen.zettel_loeschen': 'Zettel {nr} löschen?',
    'bestaetigen.zettel_zuruecknehmen': 'Den zuletzt erfassten Zettel zurücknehmen?',
    'bestaetigen.abschliessen': 'Runde abschließen? Danach lässt sich nichts mehr nachtragen. Kennzahlen, Verteilungen, Einzelwerte und Zettel bleiben zum Teilen, bis die nächste Runde beginnt.',
    'bestaetigen.abschliessen_verdeckt': 'Runde abschließen? Danach sind die Einzelwerte gelöscht, und es lässt sich nichts mehr nachtragen. Kennzahlen und Verteilungen bleiben bis zur nächsten Runde.',

    'ergebnis.titel': 'Ergebnis',
    'ergebnis.zwischenstand': 'Zwischenstand: Die Runde läuft noch.',
    'ergebnis.weiter_erfassen': 'Weiter erfassen',
    'ergebnis.abschliessen': 'Runde abschließen',
    'ergebnis.abgeschlossen': 'Runde abgeschlossen um {zeit} Uhr.',
    'ergebnis.abgeschlossen_offen': 'Einzelwerte und Zettel bleiben zum Teilen, bis die nächste Runde beginnt.',
    'ergebnis.abgeschlossen_verdeckt': 'Die Einzelwerte sind gelöscht.',
    'ergebnis.grundlage': '{g} Anwesende. In die Rangfolge kommt ein Vorschlag ab {k} Bewertungen.',
    'ergebnis.verdoppelt': 'Gezeigt wurde 0 bis 5, gerechnet wird mit dem Doppelten auf 0 bis 10, wie online.',
    'ergebnis.leer': 'Noch nichts erfasst.',
    'ergebnis.passiv_unklar': 'Die Passivlösung haben nur {n} bewertet, nötig wären {k}. Deshalb steht sie nicht in der Rangfolge, und es lässt sich nicht sagen, ob ein Vorschlag besser ist als sie.',
    'ergebnis.nur_passiv': 'Kein Vorschlag hat mehr Zustimmung als die Passivlösung. Damit bleibt es beim Bisherigen – auch das ist ein Ergebnis.',
    'ergebnis.kein_sieger': 'Bisher hat kein Vorschlag genug Bewertungen für ein belastbares Ergebnis.',
    'ergebnis.gleichstand': '{liste} liegen völlig gleichauf: gleicher Durchschnitt, gleiche niedrigste Stimme, gleich viele Stimmen unter {g}. Nach der Regel gewinnt die niedrigere Nummer. Entscheidet besser selbst, im Gespräch oder mit einer Stichrunde.',
    'ergebnis.und': ' und ',
    'ergebnis.vorschlag': 'Vorschlag',
    'ergebnis.durchschnitt': 'Durchschnitt',
    'ergebnis.sieger': 'am breitesten getragen',
    'ergebnis.zu_wenig': 'zu wenig Bewertungen',
    'ergebnis.zu_viele': 'mehr Werte als Anwesende',
    'ergebnis.gleichauf': 'gleichauf mit der Passivlösung',
    'ergebnis.nicht_legitimiert': 'weniger Zustimmung als Passivlösung',
    'ergebnis.niedrigst': 'niedrigste Stimme {w}',
    'ergebnis.unter': 'Stimmen <{g}: {n}',
    'ergebnis.bewertet_von': 'bewertet von {n} der {g}',
    'ergebnis.enthaltungen': 'Enthaltungen: {n}',
    'ergebnis.kik': 'Kraft im Konsens {w}',
    'ergebnis.verteilung_alt': 'Verteilung der Werte: {w}',
    'ergebnis.abgegeben': '{n} Bewertungen abgegeben',
    'ergebnis.abgegeben_eins': '1 Bewertung abgegeben',
    'ergebnis.teilen': 'Teilen',
    'ergebnis.wie_lesen': 'Wie lese ich das?',
    'ergebnis.erklaerung1': 'Die große Zahl sagt, wie weit die Gruppe im Schnitt mitgeht. Groß ist gut: Ganz oben steht der Vorschlag, hinter dem am ehesten alle gemeinsam stehen können. Enthaltungen zählen nicht mit, auch nicht als 0.',
    'ergebnis.erklaerung2': 'Schau auch auf die niedrigste Stimme und die Stimmen unter 2, bei 0 bis 10 unter 3. Der Schnitt allein verrät nicht, ob jemand kaum mitkommt; die Zahlen daneben tun es. Liegen zwei gleich, gewinnt, wer die Zögernden besser mitnimmt.',
    'ergebnis.erklaerung_kik': 'Die Kraft im Konsens vergleicht einen Vorschlag mit der Passivlösung. Ist sie positiv, bringt er die Gruppe weiter; ist sie negativ, wäre ihr das Bisherige lieber. Steht dort eine Null, bleibt es beim Bisherigen.',

    'teilen.titel': 'Ergebnis teilen',
    'teilen.fuehrung': 'Als Text für Mail, Messenger oder Notizen, als Datei oder gedruckt. Nichts davon läuft über einen Server: Was du teilst, verlässt das Handy nur über die App, die du dafür wählst.',
    'teilen.was': 'Was soll hinaus?',
    'teilen.stufe_a': 'Nur das Ergebnis',
    'teilen.stufe_a_dazu': 'Kennzahlen und Verteilungen, wie an der Tafel.',
    'teilen.stufe_b': 'Dazu die Einzelwerte',
    'teilen.stufe_b_dazu': 'Als Tabelle: je Zeile eine Eingabe, je Spalte ein Vorschlag, die Werte, wie sie erfasst wurden, ohne Bezug zu einer Person.',
    'teilen.stufe_c': 'Dazu die Zettel',
    'teilen.stufe_c_dazu': 'Die Zettel stehen in der Tabelle mit ihrer Nummer, je Zettel eine Person.',
    'teilen.grund_verdeckt': 'Nicht in einer verdeckten Runde.',
    'teilen.grund_abgeschlossen': 'Die Runde ist abgeschlossen, und ihre Einzelwerte sind schon gelöscht.',
    'teilen.grund_leer': 'Noch nichts erfasst.',
    'teilen.grund_keine_zettel': 'Keine Zettel erfasst.',
    'teilen.beschriftung': 'Beschriftung',
    'teilen.beschriftung_dazu': 'Freiwillig. Steht im Text und in der Tafelansicht und bleibt, bis die Sitzung endet.',
    'teilen.thema': 'Worum ging es?',
    'teilen.vorschau': 'So sieht es aus',
    'teilen.vorschau_dazu': 'Aus diesem Feld lässt sich der Text auch markieren und kopieren.',
    'teilen.unsicher': 'Das Teilen-Blatt und die Zwischenablage gibt der Browser nur über https frei. Sichern, Drucken und das Textfeld gehen trotzdem.',
    'teilen.blatt': 'Teilen …',
    'teilen.datei': 'Als Text sichern',
    'teilen.kopieren': 'Kopieren',
    'teilen.drucken': 'Drucken',
    'teilen.drucken_dazu': 'Drucken gibt die Tafelansicht aus, mit Einzelwerten und Zetteln als Anhang, wenn sie oben gewählt sind. Auf dem Handy wird daraus ein PDF.',
    'teilen.zurueck': 'Zurück zum Ergebnis',
    'teilen.geteilt': 'Geteilt.',
    'teilen.gesichert': 'Gesichert als {name}.',
    'teilen.kopiert': 'Kopiert.',
    'teilen.markiert': 'Der Text ist markiert. Jetzt kopieren.',
    'teilen.fehlgeschlagen': 'Das ging nicht. Sichern oder das Textfeld gehen immer.',
    'teilen.kopf': 'Konsensieren im Raum – Ergebnis',
    'teilen.kopf_zwischenstand': 'Konsensieren im Raum – Zwischenstand',
    'teilen.runde_vom': 'Runde vom {datum}',
    'teilen.zwischenstand_vom': 'Zwischenstand vom {datum}',
    'teilen.anwesende': '{g} Anwesende',
    'teilen.skala5': 'gezeigt 0 bis 5, gerechnet verdoppelt auf 0 bis 10',
    'teilen.skala10': 'gezeigt 0 bis 10',
    'teilen.mit_passiv': 'mit Passivlösung',
    'teilen.thema_zeile': 'Thema: {thema}',
    'teilen.rechnung': 'In die Rangfolge kommt ein Vorschlag ab {k} Bewertungen. Durchschnitt und Kraft im Konsens stehen auf 0 bis 10, Stimmen so, wie sie gezeigt wurden.',
    'teilen.schnitt': 'Durchschnitt {w}',
    'teilen.verteilung': 'Verteilung',
    'teilen.einzelwerte': 'Einzelwerte, wie erfasst: je Zeile eine Eingabe, je Spalte ein Vorschlag. Zeilen aus Karten und Händen sind Eingaben in der Reihenfolge des Erfassens, keine Personen; – ist Enthaltung, leer ist keine Eingabe.',
    'teilen.einzelwerte_zettel': 'Zettel stehen mit ihrer Nummer, je Zettel eine Person.',
    'teilen.spalte_eingabe': 'Eingabe',
    'teilen.fuss': 'Erstellt mit Konsensieren im Raum, Fassung {v}.',

    'karten.titel': 'Karten drucken',
    'karten.fuehrung': 'Ein Blatt je Person: sechs Karten von 0 bis 5 zum Ausschneiden. Die Ziffer steht schwarz auf Weiß, der Rahmen trägt die Farbe der Skala. Keine Karte zeigen heißt Enthaltung.',
    'karten.druck': 'Druck',
    'karten.farbe': 'Farbe',
    'karten.sw': 'Schwarz-Weiß',
    'karten.drucken': 'Drucken',
    'karten.tipp_druck': 'Schalte im Druckdialog Kopf- und Fußzeilen aus und drucke in Originalgröße, nicht „an Seite angepasst“. Für zehn Personen wählst du zehn Kopien.',
    'karten.tipp_rueckseite': 'Die Rückseite bleibt leer. So lässt sich eine Karte auch nur der Moderation zeigen.',
    'karten.karte_aria': 'Karte {w}',

    'impressum.titel': 'Impressum',
    'impressum.laeuft': 'Das Impressum wird geladen …',
    'impressum.fehler': 'Das Impressum ließ sich nicht laden ({grund}).',

    'pruefen.titel': 'Testfälle prüfen',
    'pruefen.fuehrung': 'Die App rechnet dieselben Fälle durch wie das Online-Werkzeug. Stimmen alle, bekommt eine Gruppe im Raum dieselben Zahlen wie online.',
    'pruefen.laeuft': 'Die Fälle werden gerechnet …',
    'pruefen.summe': '{n} von {g} Fällen stimmen.',
    'pruefen.nicht_geladen': 'Die Testfälle ließen sich nicht laden ({grund}).',

    'anleitung.titel': 'So funktioniert Konsensieren im Raum',
    'anleitung.fuehrung': 'Die App hilft beim systemischen Konsensieren, wenn alle im selben Raum sitzen. Die Vorschläge stehen an der Tafel, alle zeigen ihre Zustimmung mit Karten oder Fingern, und die App auf dem Handy der Moderation zählt – nach denselben Regeln wie das Online-Werkzeug.',
    'anleitung.starten': 'App starten',
    'anleitung.h_was': 'Was die App ist',
    'anleitung.was1': 'Eine Zählhilfe für das Handy der Moderation. Sie rechnet aus, was an der Tafel mühsam wäre: den Durchschnitt jedes Vorschlags, die niedrigste Stimme, die sehr niedrigen Stimmen, die Enthaltungen und den Abstand zur Passivlösung. Ein zweites Gerät, ein Konto oder eine Anmeldung braucht es nicht.',
    'anleitung.was2': 'Die App kennt keine Namen. Sie merkt sich nur Zahlen, und die Einzelwerte nur, bis die Runde abgeschlossen ist. Das Archiv bleibt die Tafel.',
    'anleitung.h_wann': 'Im Raum oder online?',
    'anleitung.wann1': 'Sitzen alle zusammen und soll heute entschieden werden, nimm die App. Sind die Leute verstreut, brauchen sie Zeit zum Nachdenken, oder sollen erst Vorschläge gesammelt und kommentiert werden, nimm das Online-Werkzeug. Beide rechnen gleich: Eine Gruppe bekommt im Raum dieselben Zahlen wie online.',
    'anleitung.zum_werkzeug': 'Zum Online-Werkzeug',
    'anleitung.zum_artikel': 'Zum Artikel über die Methode, im Online-Werkzeug',
    'anleitung.h_vorbereiten': 'Vorbereiten',
    'anleitung.vorbereiten1': 'Druck für jede Person ein Blatt mit den Karten 0 bis 5 und schneid sie aus. Wer lieber Finger zeigt, braucht keine Karten.',
    'anleitung.vorbereiten2': 'Öffne die App einmal, solange du Netz hast, und leg sie auf den Home-Bildschirm: auf dem iPhone in Safari über „Teilen“ und „Zum Home-Bildschirm“, auf Android in Chrome über das Menü und „App installieren“. Danach startet sie auch ohne Netz.',
    'anleitung.vorbereiten3': 'Schreib die Vorschläge nummeriert an die Tafel, dazu die Passivlösung P: „Es bleibt, wie es ist.“',
    'anleitung.h_runde': 'Eine Runde',
    'anleitung.runde1': 'Tipp auf „Ich moderiere“ und leg die Runde an: wie viele da sind, womit gezeigt wird und ob offen oder verdeckt. Steht nur ein Vorschlag im Raum, frag vorher, ob es Einwände gibt; bleiben alle Hände unten, ist er angenommen.',
    'anleitung.runde2': 'Geh die Zeilen der Reihe nach durch, mit P vorneweg: Alle zeigen ihre Karte, du tippst ein, was du siehst. Keine Karte heißt Enthaltung; die zählt nicht mit, auch nicht als 0.',
    'anleitung.runde3': 'Mit „Ergebnis ansehen“ erscheint die Tafelansicht. Solange die Runde läuft, lässt sich noch nachtragen und korrigieren.',
    'anleitung.runde4': 'Mit „Runde abschließen“ lässt sich nichts mehr nachtragen. Kennzahlen, Einzelwerte und Zettel bleiben zum Abschreiben und Teilen stehen, bis die nächste Runde beginnt; in einer verdeckten Runde sind die Einzelwerte mit dem Abschluss gelöscht.',
    'anleitung.h_erfassen': 'Drei Arten zu erfassen',
    'anleitung.erfassen_vorschlag': '„Vorschlag 3, Karten hoch.“ Ein Tipp je Person; der Zähler zeigt, wie viele erfasst sind, und Rückgängig nimmt den letzten Tipp zurück. Gut bis etwa zehn Personen.',
    'anleitung.erfassen_wert': '„Wer hat 5? Wer hat 4?“ Du trägst ein, wie viele Hände oben sind. Das dauert länger, aber erhobene Hände lassen sich auch in größeren Runden zählen.',
    'anleitung.erfassen_person': 'Ein ganzer Zettel am Stück, etwa wenn jemand seine Werte ansagt oder das Handy verdeckt als Urne herumgeht.',
    'anleitung.h_lesen': 'Das Ergebnis lesen',
    'anleitung.lesen1': 'Die große Zahl ist der Durchschnitt, immer auf der Skala von 0 bis 10: wie weit die Gruppe mitgeht. Ganz oben steht, was am breitesten getragen wird.',
    'anleitung.lesen2': 'Darunter stehen die niedrigste Stimme und die Stimmen unter 2, bei 0 bis 10 unter 3. Sie zeigen, ob jemand kaum mitkommt; der Schnitt allein verrät das nicht. Die Enthaltungen stehen als Zahl dabei; mitgezählt werden sie nicht.',
    'anleitung.lesen3': 'Die Passivlösung ist die Messlatte. Nur was mehr Zustimmung hat als „es bleibt, wie es ist“, bringt die Gruppe weiter. Der Abstand heißt Kraft im Konsens.',
    'anleitung.lesen4': 'Liegen die ersten beiden völlig gleichauf, sagt die App es dazu. Dann entscheidet ihr besser selbst, im Gespräch oder mit einer Stichrunde der beiden.',
    'anleitung.h_teilen': 'Das Ergebnis teilen',
    'anleitung.teilen1': 'In der Tafelansicht führt „Teilen“ zu einem Text mit allen Kennzahlen, in offenen Runden wahlweise mit den Einzelwerten und Zetteln, auch nach dem Abschluss noch. Den Text gibst du über das Teilen-Blatt des Handys weiter, sicherst ihn als Datei, kopierst ihn oder druckst die Tafelansicht; auf dem Handy wird daraus ein PDF. Ohne Netz geht das genauso: Eine Mail wartet im Postausgang, eine Notiz bleibt auf dem Handy.',
    'anleitung.teilen2': 'Ein Thema und Titel für die Zeilen kannst du dazu eintippen; sie stehen im Text und in der Tafelansicht und verschwinden mit der Sitzung. Das Teilen-Blatt und das Kopieren gibt der Browser nur über eine gesicherte Adresse (https) frei; über http bleiben Sichern, Drucken und das Textfeld. Zeigt Safari die gesicherte Datei nur an, führt „Teilen“ oben rechts zu „In Dateien sichern“.',
    'anleitung.h_skala': 'Warum 0 bis 5 reicht',
    'anleitung.skala1': 'Karten und eine Hand zeigen 0 bis 5, gesagte Zahlen 0 bis 10. Bei 0 bis 5 rechnet die App mit dem Doppelten, damit das Ergebnis zur Skala von 0 bis 10 passt. Bis etwa zehn Personen ändert das am Ergebnis praktisch nichts; nur Gleichstände werden etwas häufiger. In einer Runde gilt eine Skala für alle.',
    'anleitung.h_offen': 'Offen oder verdeckt',
    'anleitung.offen1': 'Offen zeigen alle ihre Karte in den Raum. Verdeckt zeigen sie sie nur dir – die Rückseite der Karten ist leer –, oder das Handy geht als Urne herum. Dann stehen beim Erfassen nur Zähler auf dem Schirm und im Ergebnis nur Verteilungen und Kennzahlen.',
    'anleitung.h_merken': 'Was die App sich merkt',
    'anleitung.merken1': 'Nur Zahlen und, wenn du sie eintippst, Thema und Titel der Vorschläge; nur auf deinem Handy, keine Namen. Mit der nächsten Runde sind die Einzelwerte der vorigen weg, in verdeckten Runden schon mit dem Abschluss; mit „Sitzung beenden“ alles. Nach zwölf Stunden ohne Eingabe vergisst die App alles von selbst.',
    'anleitung.h_grenzen': 'Was noch nicht geht',
    'anleitung.grenzen1': 'Noch hat nur die Moderation ein Handy in der Hand. Dass alle auf dem eigenen Handy bewerten und einen QR-Zettel zeigen, kommt als Nächstes.',
    'anleitung.grenzen2': 'Ohne Netz startet die App nur, wenn sie über eine gesicherte Adresse (https) geöffnet wurde; das verlangen die Browser. Über http im WLAN, etwa vom eigenen Rechner aus, braucht sie das Netz bei jedem Start.',

    // Wortleiter des Werkzeugs, fuer Vorleseprogramme an den Tasten.
    'skala.wert0': 'geht gar nicht für mich',
    'skala.wert1': 'das trage ich kaum noch mit',
    'skala.wert2': 'große Bedenken',
    'skala.wert3': 'deutliche Bedenken',
    'skala.wert4': 'eher nicht',
    'skala.wert5': 'gemischte Gefühle',
    'skala.wert6': 'eher dafür',
    'skala.wert7': 'ja, das trage ich mit',
    'skala.wert8': 'gerne',
    'skala.wert9': 'sehr gerne',
    'skala.wert10': 'voll dabei, da bin ich ganz dafür'
  };

  /* Ein fehlender Schluessel zeigt sich selbst, statt still leer zu bleiben;
     tools/test.js prueft ausserdem, dass jeder benutzte Schluessel da ist. */
  function t(schluessel, werte) {
    const text = DE[schluessel];
    if (text === undefined) return schluessel;
    return text.replace(/\{(\w+)\}/g, function (ganz, name) {
      return werte && name in werte ? String(werte[name]) : ganz;
    });
  }

  function fuellen(wurzel) {
    wurzel.querySelectorAll('[data-t]').forEach(function (el) { el.textContent = t(el.dataset.t); });
    wurzel.querySelectorAll('[data-t-aria]').forEach(function (el) {
      el.setAttribute('aria-label', t(el.dataset.tAria));
    });
    const titel = wurzel.querySelector('title[data-t]');
    if (titel) document.title = titel.textContent;
  }

  return { de: DE, t: t, fuellen: fuellen };
}));
